name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala: [ 2.12.14 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
      - name: Cache
        uses: coursier/cache-action@v5
      - name: Test
        run: sbt test

  doc:
    name: Documentation and formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
      - name: Check Formatting
        run: sbt scalafmtCheckAll

  all_test_passed:
    name: "all tests passed"
    runs-on: ubuntu-latest
    needs: [test, doc]
    steps:
      - run: echo Success
